# Generated by Django 5.2.1 on 2025-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('framework', 'Framework'), ('language', 'Programming Language'), ('tool', 'Tool'), ('other', 'Other')], max_length=50)),
                ('color', models.CharField(default='#3498db', help_text='Hex color for UI', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('description', models.TextField(help_text='Brief project description')),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed project explanation')),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('development', 'In Development'), ('completed', 'Completed'), ('maintenance', 'Maintenance'), ('archived', 'Archived')], default='development', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers show first')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('thumbnail', models.ImageField(blank=True, upload_to='project_thumbnails/')),
                ('screenshots', models.TextField(blank=True, help_text='JSON array of screenshot URLs')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='main.technology')),
            ],
            options={
                'ordering': ['-priority', '-created_date'],
            },
        ),
    ]
